### ISSUE TITLE
System proxy is not bypassed

### ISSUE THREAD

**Issue by minami-o** [FelisCatus/SwitchyOmega#1178] opened 2017-08-16 09:15 UTC
Hi there, and thanks for the hard work!
I'm using Firefox nightly (57.0a1 at the time of this post), and I have a distant proxy with a PAC configuration file: the PAC file recovery works fine, and the PAC profile seems to be created correctly.
I am using it on Windows 10 with a system proxy by Websense which does HTTPS interception: when no proxy is set up (either on FF or SwitchyOmega), this (righteously) triggers an error on Firefox because MITM is bad :)
When my proxy is set up via a PAC file on firefox (using network.proxy.type=2 and network.proxy.autoconfig_url), the expected behaviour is met, ie. the connection goes through my proxy and bypasses the system proxy.
When my proxy is set up with the PAC profile I created in SwitchyOmega (with network.proxy.type reset to 5, obviously), I still get the MITM message from Firefox.
My issue is therefore that, unlike the native PAC feature of Firefox, SwitchyOmega doesn't seem to be able to bypass the system proxy, which makes it pretty useless in my case…
Could you please explain to me why this does not work and see if you can correct this in a future version?
I'll be happy to test any update if needed.
Thanks in advance!

SwitchyOmega 2.5.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://addons.cdn.mozilla.net",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment] 2017-08-19 00:47
1: PAC Profiles are NOT supported in Firefox. #1146 will be released soon which shows you errors about this. Please see #1146 for the explanation.

2: We are having issues regarding using SwitchyOmega on windows platforms, namely #1171. The issue is on Firefox's side. If you are affected, then SwitchyOmega will not work for you regardless of configuration, even if you don't use PAC Profile.

For now, please stick to your PAC script and please watch the two issues above to be notified when you can actually start using SwitchyOmega.

**Closed by FelisCatus** 2017-08-19 00:47 UTC
