### ISSUE TITLE
Lag while using the extension,

### ISSUE THREAD

**Issue by anupkrgupta11** [FelisCatus/SwitchyOmega#445] opened 2015-05-06 09:58 UTC
SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by FelisCatus** [comment] 2015-05-06 12:08
Please let me know the exact action that lags. Is switching profiles slow? Or are you experiencing delay before you visit the first few websites on startup?

**Comment by rfreitas** [comment] 2015-05-07 07:39
My browser becomes unresponsive when I visit imggur. The failed resources counter also fires up when the page is unresponsive (easily goes to 200). Turning off this feature seems to have helped.

**Comment by FelisCatus** [comment] 2015-05-07 14:25
@rfreitas Didn't happen for me on imgur though. Are the images failing to load?

**Comment by rfreitas** [comment] 2015-05-07 16:28
Eventually the website loads after it unfreezes, including the images. I'm using a pac file, it's a chinese proxy provider called qujing.

**Comment by rfreitas** [comment] 2015-05-07 16:36
![screen shot 2015-05-08 at 00 34 19](https://cloud.githubusercontent.com/assets/651348/7520570/22e9b796-f51a-11e4-97d5-d071d54bb848.png)
Once the counter starts to go crazy the website does not respond. Actually it seems to lead fully before it goes crazy and freezes. This bug might not be related to the original one, sorry about that.

**Comment by FelisCatus** [comment] 2015-05-08 07:11
@rfreitas I tried the exact URL in your screenshot but it still didn't happen to me. I think a conflicting or broken extension that sends tons of web requests might be the cause. Please try disabling all extension except SwitchyOmega and reload the website to see if it happens again. Then you can try enabling the extensions one by one to locate the problem if that's the case.

**Comment by PaulUlrik** [comment] 2015-05-09 12:00
没想到项目作者英语也这么牛逼... 请允许我膜拜一下。

**Comment by FelisCatus** [comment] 2015-08-25 06:08
I'm closing this issue because it seems abandoned by its original reporter while still lacking important information. Please do reopen if you have more information or questions.

**Closed by FelisCatus** 2015-08-25 06:08 UTC

**Comment by rfreitas** [comment] 2015-08-25 06:23
Sorry I forgot about the test. Nonetheless, I haven't seen the issue since, so it might have been an extension that got bug fixed. Possible Hover Zoom, since it's the only image related extension I have.

**Comment by FelisCatus** [comment] 2015-08-25 06:31
I'm glad to hear that the problem has been solved for you. If you still have any questions or experience other issues, please feel free to comment.

P.S. It is not the first time for SwitchyOmega to successfully report issues of other extensions for repeatedly making web requests like crazy. Who knows, SwitchyOmega might become a industrial standard for detecting such bugs. :wink:
