### ISSUE TITLE
Problem with credential containing uppercase 

### ISSUE THREAD

**Issue by elarichiy** [FelisCatus/SwitchyOmega#567] opened 2015-08-31 15:20 UTC
hello, 
SwitchyOmega always submit to proxy server usernames in lowercase , so if I have a username containing Uppercase characters it keeps showing credentials dialog.

**Comment by FelisCatus** [comment] 2015-09-04 03:24
This is likely to be a Chrome problem. One question though: Does it work when you disable authentication in SwitchyOmega, and use the credentials dialog instead?

**Comment by elarichiy** [comment] 2015-09-08 09:09
hello, Yes it works

**Comment by FelisCatus** [comment] 2015-09-09 08:58
Seems Chrome trying to convert username provided by extensions to all-lowercase. I need to check this later myself and report an issue on Chrome Proxy API for that.

For now, the problem cannot be solved on SwitchyOmega's side. You would have better luck with all-lowercase usernames.

**Comment by celeron533** [comment] 2015-09-09 09:44
How about using **URL encoding**?

**Comment by FelisCatus** [comment] 2015-09-09 10:30
I don't think Chrome Proxy API allows URL encoded credentials.

**Comment by FelisCatus** [comment] 2016-03-15 06:35
Hey, I can't reproduce this on my side. From my own observation, both the username and password are handled as-is to Chrome and both are case-sensitive.

Environment: Polipo, Chrome 49.0.2623.87, Linux.

**Comment by FelisCatus** [comment] 2016-04-20 05:38
Any updates?

**Comment by FelisCatus** [comment] 2017-03-12 04:44
Closing this since there are no updates. This can't be fixed in SwitchyOmega itself anyway.

**Closed by FelisCatus** 2017-03-12 04:44 UTC
