### ISSUE TITLE
Delete button doesn't delete one profile

### ISSUE THREAD

**Issue by cinqs** [FelisCatus/SwitchyOmega#1386] opened 2018-03-01 09:07 UTC
recently accidentally added a new profile, and I tried to remove it with the **Delete** button in the upper right corner of the *Profile* tab. 

but after a restart of the browser or reload the page, or simply exit the page and go in again.

The profile will still be there

this doesn't bother much, but please fix it.

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36

**Comment by FelisCatus** [comment] 2018-03-12 03:28
First, after you delete the profile, please right-click on the SwitchyOmega icon and select Save error log and upload it here.

Then, Please turn off synchronization in Options > Import/Export and see if it helps. If it helps, it might be the case with synchronization.

**Comment by cinqs** [comment] 2018-03-13 07:28
[OmegaLog_1520925727046.txt](https://github.com/FelisCatus/SwitchyOmega/files/1805877/OmegaLog_1520925727046.txt)

Please see updates. and the `Syncing` was disabled by default, after enabling the button, the *test* profile was deleted successfully

**Comment by FelisCatus** [comment] 2018-03-29 03:59
Okay, what's happening here is I don't even see a delete request in the log. This is weird and I can't figure out what's going on.

Is the error still reproducible on your side? Could you please open Developer Tools, click on the Console tab and then attempt the deletion?

**Comment by cinqs** [comment] 2018-03-29 07:33
Yes, The error is still there, and I am trying to produce a gif screenshot of the browser.

For your info, I am using this extension on another my laptop which was signed with the same chrome google user. Anytime I click on the "Sync" button, the profiles from the other laptop was synced to this one. And I have to change it back manually.

**Comment by cinqs** [comment] 2018-03-29 07:43
see this video below plz

https://drive.google.com/file/d/1_0FS76eVhZQDYLnxuNaorKpcxwvHJEx2/view

**Comment by cinqs** [comment] 2018-03-29 07:52
I may noticed the difference within the two actions I made... the first time I hit delete and leaved it there, the second time after I hit delete button, I clicked again the apply changes button, then the delete action will be applied? is it the logic?

**Comment by FelisCatus** [comment] 2018-03-30 04:50
@cinqs Basically, changes will only be applied when you click on Apply Changes. It's like the save button.

However, normally when you try to close/refresh the options window without applying first, it should show you an alert asking whether you really want to do that, like below. I did not see that happening. Did you ever select "prevent this website from showing dialogs" as shown below? If so, that must have disabled any dialogs like that.

![image](https://user-images.githubusercontent.com/912649/38125004-f363db38-339a-11e8-83ac-970d1e6065c1.png)

Anyway, this is working as intended so I'm closing this for now. By the way, you should keep Synchronization disabled if you intend to use different options on different machines.

**Closed by FelisCatus** 2018-03-30 04:50 UTC

**Comment by cinqs** [comment] 2018-03-30 06:45
Yes, I can recall this dialog alert popping out once. it's my mistake not to take it seriously. The reason you didn't see this dialog in the webm video is I only recorded the content in the tab.

Thank you for your effort, and sorry for the confusion I made. I will turn off the syncing option.
