### ISSUE TITLE
Timeout on HTTPS requests through OWASP ZAP

### ISSUE THREAD

**Issue by dhjw** [FelisCatus/SwitchyOmega#1532] opened 2018-06-24 16:05 UTC
I've configured an HTTPS proxy to [OWASP ZAP](https://www.owasp.org/index.php/OWASP_Zed_Attack_Proxy_Project) (localhost:8080) but all requests timeout on the client side. HTTP requests work fine, and it works fine if I disable SwitchyOmega and use a system proxy to do the same thing.

SwitchyOmega 2.5.14
Mozilla/5.0 (X11; CrOS armv7l 10452.99.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.203 Safari/537.36

**Comment by FelisCatus** [comment] 2018-06-26 02:46
Please take a look at `chrome://net-internals/#proxy` with SwitchyOmega disabled. Then enable SwitchyOmega and check `chrome://net-internals/#proxy` again. If it is the same, then the issue is not with SwitchyOmega. If it is not, then you'd probably need to change the options in SwitchyOmega to make it the same.

I don't know the exact configuration that would work for you, but most of the cases you will want to fill in the first line and only the first line in SwitchyOmega. Note that the protocol is the protocol of the proxy, not the URLs. Most of the times, the protocol should be "HTTP", so try that first before moving to "HTTPS".

**Comment by dhjw** [comment] 2018-06-26 02:58
Hi, the issue appears to be SwitchyOmega prepending "https://" to the proxy host.

[With SwitchyOmega](https://i.imgur.com/nBjdHJb.png)
[With no proxy extension](https://i.imgur.com/VVmGrQq.png)
[With SwitchSharp (works)](https://i.imgur.com/AtSxXfh.png)

**Comment by FelisCatus** [comment] 2018-06-26 03:02
@dhjw In that case, please follow the recommendation in my comment above to set the proxy protocol to `HTTP`. Please allow me to emphasize again that the protocol is for the proxy, not for the URLs.

See recommended settings below. Note the protocol on the second line.

![image](https://user-images.githubusercontent.com/912649/41886761-9f9741f4-78b2-11e8-805e-32b3e6e7705b.png)

**Comment by FelisCatus** [comment] 2018-06-26 03:03
Sorry, wrong screenshot. See below.

![image](https://user-images.githubusercontent.com/912649/41886795-c7a42126-78b2-11e8-8a94-31db62654b1d.png)

**Closed by FelisCatus** 2018-06-26 03:02 UTC

**Comment by dhjw** [comment] 2018-06-26 03:08
The suggestion does work, but it's still unexpected and appears to make it impossible to manually specify the https:// scheme proxy separately like one can in the system or SwitchySharp.

Thanks

**Comment by FelisCatus** [comment] 2018-06-26 03:13
@dhjw See the updated screenshot. It is definitely possible to separately specify different proxies for different schemes, as clearly shown in the screenshot above. Each line would apply to a different URL scheme.

Actually, the SwitchyOmega options can do everything that you can do with the system or SwitchySharp settings, and it additionally gives you the freedom to specify the protocol of the proxy itself. Unfortunately, it also leads to confusion between the protocol and the scheme, which would lead to cases like the one discussed in this issue.

**Comment by dhjw** [comment] 2018-06-26 03:15
I understand, thanks
