### ISSUE TITLE
WebSocket not proxied on Firefox

### ISSUE THREAD

**Issue by HouQiming** [FelisCatus/SwitchyOmega#1387] opened 2018-03-02 10:19 UTC
When I set a switch rule for a LAN site, the `http://` requests are proxied but the `ws://` requests are not.

It's fine in Chrome.

SwitchyOmega 2.5.10
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://raw.githubusercontent.com",
    "level": "warn"
}
```

**Comment by HouQiming** [comment] 2018-03-02 10:23
It only happens in auto-switch mode, it works if I set that proxy globally.

**Comment by FelisCatus** [comment] 2018-03-12 03:20
Could you please share the switch rule in question?

**Comment by HouQiming** [comment] 2018-03-12 03:24
The proxy:

The rule:

```
192.168.0.133 +LAN proxy
```

**Comment by FelisCatus** [comment] 2018-03-12 03:33
One question -- does it work if you create and use a new Switch Profile with no rules and with "LAN proxy" as the default profile?

**Comment by HouQiming** [comment] 2018-03-12 03:38
No, it doesn't. Same symptom as my previous switch profile.

**Comment by HouQiming** [comment] 2018-03-12 03:39
The new profile is supposed to look like this, right?

```
[SwitchyOmega Conditions]
@with result


* +LAN proxy
```

**Comment by FelisCatus** [comment] 2018-03-12 03:40
Yes

**Comment by FelisCatus** [comment] 2018-03-12 03:55
Okay, I did a little experiment in Firefox Nightly 60.0a1 (2018-01-27) and found that the proxy script correctly receives `ws://192.168.0.133` as the URL and `192.168.0.133` as the host. With the right settings, SwitchyOmega did instruct Firefox to use the proxy for the WebSocket connection.

However, my proxy is not compatible with WebSocket so I cannot test if the connection actually works or not. What software are you using for proxy server? I may also get that for testing.

Also, instead of your local WebSocket server, can you also try the [this testing website](http://www.websocket.org/echo.html)? Try to click "Connect" and then "Send" to see if it works. You can try this with Direct Connection, and then your Proxy Profile, and then the brand new Switch Profile with no rules. See if anything differs.

Also, it might be the case that there was a bug in Firefox that got fixed in the nightly. Could you please try it in Nightly and see if that's the case?

Thank you very much for the details and my apologies for not being able to reproduce the issue on my side.

**Comment by HouQiming** [comment] 2018-03-12 05:16
Come to think of it, my proxy doesn't support websocket either, but it
miraculously worked in Chrome. Maybe it's Chrome using CONNECT for
websocket?

I wrote that proxy myself. I'll do some detailed test later on the proxy
side.

**Comment by HouQiming** [comment] 2018-03-12 07:35
Detailed test result:
- When using SwitchyOmega, the proxy didn't receive any request corresponding to the websocket port
- With SwitchyOmega disabled and Firefox reconfigured to use that proxy globally, the proxy (which doesn't support WebSocket natively) received a "CONNECT" request for that websocket port, and everything worked. It shouldn't be possible for a proxy to "not support websocket". It's proxied exactly like HTTPS.
- www.websocket.org/echo.html only works with Direct Connection
- I installed Firefox Nightly and the newest version of SwitchyOmega on a new VM, it doesn't work either. Exactly the same symptom.

Attached is a Firefox profile and a proxy written in node.js to reproduce the problem (it's actually a 7z):
[upload.zip](https://github.com/FelisCatus/SwitchyOmega/files/1801755/upload.zip)

To use it:
- Extract the content to C:\ (preferably in a VM)
- Install node.js
- Run `node c:\proxy\standalone_proxy.js`
- Run `firefox -profile c:\test_profile`

By default, the profile uses SwitchyOmega and websocket doesn't work. You can then go to "about:addons" and disable SwitchyOmega. Firefox should then use the same proxy `127.0.0.1:8559` globally and websocket should work.

**Comment by FelisCatus** [comment] 2018-03-29 04:01
If only direct works, then I think the issue is not related to the switching features in SwitchyOmega. It may be the case that all WebExtensions suffer from the same problem.

It may be helpful to build a minimal reproducible case with one simple WebExtension instead of SwitchyOmega. [Here](https://bugzilla.mozilla.org/attachment.cgi?id=8906727) you can find one WebExtension that always return "DIRECT" and you can change it return "PROXY 192.168.xxx.xxx:8558" to see if it works. If the proxy is correctly set but WebSocket does not work, please open a new bug at Bugzilla.

**Comment by FelisCatus** [comment] 2018-07-09 05:53
SwitchyOmega 2.5.16 released with the new `browser.proxy.onRequest` API on Firefox. Please upgrade to FF 60+ and latest SwitchyOmega. If you still observe this issue, please let me know.

**Closed by FelisCatus** 2018-07-09 05:53 UTC

**Comment by z1kk0** [comment] 2019-12-06 19:24
I can confirm this bug on Firefox 68.2esr. If I use direct connection or connection through Firefox proxy settings - it works like a charm but not through SwitchyOmega. There is not such problem on Chrome/Chromium
