### ISSUE TITLE
PAC script only authenticates for pure hostname, not for paths

### ISSUE THREAD

**Issue by wickles** [FelisCatus/SwitchyOmega#806] opened 2016-06-17 00:38 UTC
I don't know how PAC scripts typically work, but my PAC script reads the hostname and checks if it matches some specific host. If I navigate to the pure hostname, it shows me the usual authentication page and then redirects me to where I was going. But if I navigate to a path under the host before navigating, it doesn't seem to work. 

![screen shot 2016-06-16 at 5 23 55 pm](https://cloud.githubusercontent.com/assets/4229542/16137499/e44a9334-33e8-11e6-9ce0-52aca39015aa.png)

This is how the script looks: 

```
function FindProxyForURL(url, host) {
var p = "PROXY p1.proxy.mycompany.com:8080";
var h = host.toLowerCase();
if (dnsDomainIs(h,"proxy.mycompany.com")) { return "DIRECT"; }
...
if (h == "scholar.google.com" || dnsDomainIs(h,".scholar.google.com")) return p;
...
```

I'm just showing the one example here, but I'm pretty sure it happens for other hosts too. I was using this script via my OS before and never had this sort of issue. Can I change some settings in Switchy maybe?

**Comment by FelisCatus** [comment] 2016-06-18 06:49
First, make sure that you are using the PAC script as a PAC Profile in SwitchyOmega, and it is selected and activated through the popup menu.

Could you check `chrome://net-internals/#proxy` and see if it shows you anything related to PAC script? You may also disable SwitchyOmega and set the PAC settings in your OS. Refresh the page to see if anything changes.

If all the settings (except SOURCE) are exactly the same, the issue is not related to SwitchyOmega. SwitchyOmega is a configuration tool and does not do network internals. As a result, I cannot tell the reason behind `ERR_TUNNEL_CONNECTION_FAILED`.

**Comment by FelisCatus** [comment] 2016-11-09 00:26
Closing this for now. Please reopen if you have more information.

**Comment by wickles** [comment] 2016-11-09 02:45
Hi, sorry I meant to get back to this before.. 

With SO proxy my `chrome://net-internals/#proxy` shows: 
```
PAC script: data:application/x-ns-proxy-autoconfig;base64,{{long base64 string ~100k chars}}
```

With system proxy I get simply: 
```
PAC script: http://proxy.ucla.edu/cgi/proxy
Source: SYSTEM
```

So it looks very different. 

What do you mean by: 

> To minimize the difference, it is also recommended to use `file:///` URL to point to your local file containing the script, instead of copy and pasting the content into SO.

I don't copy/paste anything, I just give SO the proxy URL and it handles the rest, and shows me the downloaded contents. Do you mean it would work better to load the proxy script to a file and give it a `file:///` URL?

**Comment by FelisCatus** [comment] 2016-11-09 06:40
Great, thanks for the information.

Can you try to download the script and paste the content into the PAC Profile in SwitchyOmega? Also, please make sure you are selecting the name of your PAC Profile in the dropdown menu (instead of `Auto Switch`, `Direct`, etc.).

**Comment by wickles** [comment] 2017-02-03 23:32
I think I found the issue. The script checks domains like this: 
```
if (h == "nature.com" || dnsDomainIs(h,".nature.com")) return p;
if (h == "scholar.google.com" || dnsDomainIs(h,".scholar.google.com")) return p;
```
So when I go to `nature.com` it redirects me to `www.nature.com` which works, but when I go to `scholar.google.com` it doesn't work (as in original report). However when I try `www.scholar.google.com` (which actually just redirects to `scholar.google.com`) it works. So it seems the `h == ...` check isn't triggering for some reason and `dnsDomainIs` doesn't work when there is no `www.` prefix. 

I just checked that the same issue occurs through the system proxy so I guess it is technically a bug with the PAC script and not with SO? Maybe SO could strip leading dots from the `dnsDomainIs` check, if that would work?

**Comment by wickles** [comment] 2017-02-03 23:50
Okay.. it looks like there is also some complicated interplay with HTTPS. When I disable HTTPS-everywhere all the scenarios described in the previous comment work fine. But even with HTTPS-everywhere disabled, it fails when I navigate to `https://scholar.google.com`.

**Comment by wickles** [comment] 2017-02-04 00:15
I guess this is related to #845 but it should still work given the base URL/hostname right? How can I print the `url` and `host` passed to `FindProxyForURL` to check what's going on?

**Comment by FelisCatus** [comment] 2017-02-04 03:52
You can put `alert(host);` in your PAC script to see what's going on. Those alerts will be printed in `chrome://net-internals/#events`.

And yes, in your case it should work with the base hostname. Also, please note that if it also happens in system proxy, then there's nothing SwitchyOmega can do. The best way around this would be fixing the script.
Also, it might be the proxy server which is misbehaving. In that case, you can try to run a local proxy server and use the provided one as upstream and see if that would fix it.

**Closed by FelisCatus** 2017-02-04 03:52 UTC

**Comment by wickles** [comment] 2017-02-04 04:09
Huh.. It looks like it is parsing it correctly: 
```
message = "url: 'https://scholar.google.com/', host: 'scholar.google.com', h: 'scholar.google.com'"
```
So I guess it is probably the proxy server causing issues. Thanks.
