### ISSUE TITLE
访问ftp引起chrome崩溃

### ISSUE THREAD

**Issue by hjhjw1991** [FelisCatus/SwitchyOmega#574] opened 2015-09-02 11:53 UTC
再现方式：用域名访问ftp(ftp://example.com)，在开启扩展但并未选择情景模式的时候，引起chrome崩溃。
再现概率：100% (6/6)
关闭扩展后现象消失。

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36

**Comment by celeron533** [comment] 2015-09-02 12:29
Unable to reproduce on my machine. Maybe caused by other extension's conflict?

![image](https://cloud.githubusercontent.com/assets/3608762/9631105/4d486084-51b1-11e5-93d0-adc5785685d8.png)

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36

**Comment by hjhjw1991** [comment] 2015-09-02 12:51
I tried again right now. It disappeared. It seems that the problem just occurred during that very period.

**Comment by celeron533** [comment] 2015-09-02 15:11
Followed by the instructions from @hjhjw1991 , now I could reproduce the bug.

I'm using FileZilla as FTP server and enabled the password for FTP users.

And if I embedded the username and password string into ftp address, it works well while enabled SwitchyProxy. Otherwise, if the FTP password form is required, Chrome crashes.
> ftp://test:test@127.0.0.1:21

```
(000031)2015/9/2 22:52:41 - (not logged in) (127.0.0.1)> Connected on port 21, sending welcome message...
(000031)2015/9/2 22:52:41 - (not logged in) (127.0.0.1)> 220-FileZilla Server 0.9.53 beta
(000031)2015/9/2 22:52:41 - (not logged in) (127.0.0.1)> 220-written by Tim Kosse (tim.kosse@filezilla-project.org)
(000031)2015/9/2 22:52:41 - (not logged in) (127.0.0.1)> 220 Please visit https://filezilla-project.org/
(000031)2015/9/2 22:52:46 - (not logged in) (127.0.0.1)> USER test
(000031)2015/9/2 22:52:46 - (not logged in) (127.0.0.1)> 331 Password required for test
(000031)2015/9/2 22:52:52 - (not logged in) (127.0.0.1)> PASS ****
(000031)2015/9/2 22:52:52 - test (127.0.0.1)> 230 Logged on
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> SYST
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> 215 UNIX emulated by FileZilla
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> PWD
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> 257 "/" is current directory.
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> TYPE I
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> 200 Type set to I
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> SIZE /
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> 550 File not found
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> CWD /
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> 250 CWD successful. "/" is current directory.
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> PASV
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> 227 Entering Passive Mode (127,0,0,1,252,14)
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> LIST -l
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> 150 Opening data channel for directory listing of "/"
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> 226 Successfully transferred "/"
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> QUIT
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> 221 Goodbye
(000031)2015/9/2 22:53:00 - test (127.0.0.1)> disconnected.
(000032)2015/9/2 22:53:07 - (not logged in) (127.0.0.1)> Connected on port 21, sending welcome message...
(000032)2015/9/2 22:53:07 - (not logged in) (127.0.0.1)> 220-FileZilla Server 0.9.53 beta
(000032)2015/9/2 22:53:07 - (not logged in) (127.0.0.1)> 220-written by Tim Kosse (tim.kosse@filezilla-project.org)
(000032)2015/9/2 22:53:07 - (not logged in) (127.0.0.1)> 220 Please visit https://filezilla-project.org/
(000032)2015/9/2 22:53:13 - (not logged in) (127.0.0.1)> USER test
(000032)2015/9/2 22:53:13 - (not logged in) (127.0.0.1)> 331 Password required for test
(000032)2015/9/2 22:53:19 - (not logged in) (127.0.0.1)> PASS ****
(000032)2015/9/2 22:53:19 - test (127.0.0.1)> 230 Logged on
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> SYST
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> 215 UNIX emulated by FileZilla
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> PWD
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> 257 "/" is current directory.
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> TYPE I
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> 200 Type set to I
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> SIZE /DisplayDriver
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> 550 File not found
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> CWD /DisplayDriver/
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> 250 CWD successful. "/DisplayDriver" is current directory.
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> PASV
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> 227 Entering Passive Mode (127,0,0,1,212,57)
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> LIST -l
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> 150 Opening data channel for directory listing of "/DisplayDriver"
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> 226 Successfully transferred "/DisplayDriver"
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> QUIT
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> 221 Goodbye
(000032)2015/9/2 22:53:27 - test (127.0.0.1)> disconnected.
(000033)2015/9/2 22:53:51 - (not logged in) (127.0.0.1)> Connected on port 21, sending welcome message...
(000033)2015/9/2 22:53:51 - (not logged in) (127.0.0.1)> 220-FileZilla Server 0.9.53 beta
(000033)2015/9/2 22:53:51 - (not logged in) (127.0.0.1)> 220-written by Tim Kosse (tim.kosse@filezilla-project.org)
(000033)2015/9/2 22:53:51 - (not logged in) (127.0.0.1)> 220 Please visit https://filezilla-project.org/
(000033)2015/9/2 22:53:57 - (not logged in) (127.0.0.1)> USER test
(000033)2015/9/2 22:53:57 - (not logged in) (127.0.0.1)> 331 Password required for test
(000033)2015/9/2 22:54:03 - (not logged in) (127.0.0.1)> PASS ****
(000033)2015/9/2 22:54:03 - test (127.0.0.1)> 230 Logged on
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> SYST
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> 215 UNIX emulated by FileZilla
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> PWD
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> 257 "/" is current directory.
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> TYPE I
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> 200 Type set to I
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> SIZE /DisplayDriver/355.60
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> 550 File not found
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> CWD /DisplayDriver/355.60/
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> 250 CWD successful. "/DisplayDriver/355.60" is current directory.
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> PASV
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> 227 Entering Passive Mode (127,0,0,1,247,158)
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> LIST -l
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> 150 Opening data channel for directory listing of "/DisplayDriver/355.60"
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> 226 Successfully transferred "/DisplayDriver/355.60"
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> QUIT
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> 221 Goodbye
(000033)2015/9/2 22:54:11 - test (127.0.0.1)> disconnected.
```

**Comment by FelisCatus** [comment] 2015-09-04 05:03
This is likely to be a bug in Chromium and cannot be fixed on SwitchyOmega's side. Please open an issue on the chromium project with the crash report attached. Be sure to mention that SwitchyOmega is only used to set the proxy settings to DIRECT, and it does not change or interact with the web page in any way.

**Comment by UncleBill** [comment] 2015-11-06 18:02
ftp协议下载文件出现：

![no-supported-proxies](https://cloud.githubusercontent.com/assets/1141198/11004473/65ae4222-84f3-11e5-9117-b14abdc86f49.png)

文件地址： [ftp://ftp.vim.org/pub/vim/pc/gvim74.exe]()

**Comment by celeron533** [comment] 2015-11-07 01:52
@UncleBill 这看上去是你的代理服务器不支持ftp中转？

**Comment by UncleBill** [comment] 2015-11-07 02:13
很明显不是。我换成switchysharp就可以了

2015-11-07 9:52 GMT+08:00 Allen Zhu <notifications@github.com>:

**Comment by FelisCatus** [comment] 2015-11-07 07:53
@UncleBill 此 issue 是关于 Chrome 崩溃问题的，且无法在 SwitchyOmega 这一侧解决。而您所说的问题是`ERR_NO_SUPPORTED_PROXIES`，而这个问题可能是由于 SwitchySharp 和 SwitchyOmega 的代理设置模型不同导致的。让我们建立一个新的 issue 讨论这个问题吧？另外请在 SS 和 SO 中分别打开`chrome://net-internals/#proxy`，并将里面的文字内容复制到新 issue 中，以便比较不同实际代理设置对于FTP访问的影响。

**Comment by FelisCatus** [comment] 2016-03-08 08:47
@hjhjw1991 现在还 crash 吗？

**Comment by hjhjw1991** [comment] 2016-03-08 09:21
@FelisCatus 谢谢提醒，刚刚测试已经可以正常登陆.   
SwitchyOmega 2.3.16  
Chrome/48.0.2564.109 m

**Closed** 2016-03-08 09:33 UTC
