### ISSUE TITLE
Quick Switch enabled in settings does not enable option in Right click menu

### ISSUE THREAD

**Issue by mscreations** [FelisCatus/SwitchyOmega#848] opened 2016-08-15 15:28 UTC
If you enable Quick Switch in options and apply the changes, Right-clicking on the icon does not have quick switch enabled. If you click that option, you then enable it (again) and if you click it again it will disable it properly.

**Comment by FelisCatus** [comment] 2016-08-19 23:31
That's correct. That menu option is a toggle and controls what LEFT-clicking the icon (or pressing the shortcut key) will do.

Please let me know if you have any problems with the current features.

**Comment by FelisCatus** [comment] 2017-02-26 06:22
Closing this for now since it is as designed. Let me know if you have any suggestion to improve it.

**Closed by FelisCatus** 2017-02-26 06:22 UTC
