### ISSUE TITLE
Save Backup Files Button not working

### ISSUE THREAD

**Issue by Arrow-Li** [FelisCatus/SwitchyOmega#1167] opened 2017-08-11 04:17 UTC
Like this GIF
Firefox 56.0b1 Windows 10 Switchy 2.5.0
![123](https://user-images.githubusercontent.com/17962902/29201209-d326c946-7e8e-11e7-8989-043960b3d7c9.gif)

**Comment by olloff** [comment] 2017-08-11 10:42
Can't confirm this for Firefox 56.0b1 Windows 10 Switchy 2.5.0. 
It can be browser or profile issue, does other files are downloading and displaying correctly? 

Can you, please, provide some additional info, for example: 

- SwitchyOmega error log (context menu on SwitchyOmega icon -> Save error log);
- part of the Browser console log (Web Developer -> Browser Console or just Ctrl + Shift + J) when this issue occurs;
- SwitchyOmega debug log (see https://github.com/FelisCatus/SwitchyOmega/issues/1144#issuecomment-320478883 for instructions).

**Comment by FelisCatus** [comment] 2017-08-12 00:44
Try clicking on the button first and then export the error log. It there's nothing interesting in it, then try the Console as mentioned by @olloff.

**Comment by Arrow-Li** [comment] 2017-08-12 09:39
[Console.txt](https://github.com/FelisCatus/SwitchyOmega/files/1219641/Console.txt)
[Debug.txt](https://github.com/FelisCatus/SwitchyOmega/files/1219640/Debug.txt)
[OmegaLog.txt](https://github.com/FelisCatus/SwitchyOmega/files/1219639/OmegaLog.txt)

**Comment by FelisCatus** [comment] 2017-08-13 00:26
Sorry, I wasn't able to spot anything there. Could you please keep the Console open, and then repeatedly click on the button for a few times to see if anything is repeatedly printed to the Console?

I noticed on thing though -- the log says `lecan@wuhu.addons.mozilla.org`. This isn't SwitchyOmega's extension ID. Could you be using a custom build or a modified version of SwitchyOmega? Please always install from [AMO](https://addons.mozilla.org/en-US/firefox/addon/switchyomega/) or [SwitchyOmega Releases](https://github.com/FelisCatus/SwitchyOmega/releases) on GitHub.

Also, I would strongly recommend you try with a clean Firefox Profile. You can do this using the Profile Manager to create a brand new profile and just install SwitchyOmega on it. It is kind of unexpected when you can't export the options but the SwitchyOmega error log works fine so I highly doubt that something has changed the options page.

**Comment by Arrow-Li** [comment] 2017-08-13 02:27
I just download it from [#1152](https://github.com/FelisCatus/SwitchyOmega/pull/1152), Beta version not able to close xpinstall.signatures.required, so I just resign it.


![123](https://user-images.githubusercontent.com/17962902/29245614-f66cd15a-8011-11e7-8298-3532445ffa0a.gif)

**Comment by olloff** [comment] 2017-08-13 03:53
@Arrow-Li Eh, you've done great, but pages' Web Console can't carry this kind of information and since its probably not SwitchyOmega bug, Debug Console of extension too. Can you repeat that with Browser Console?

I believe there is only one line associated with issue there:
`[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIAnnotationService.setPageAnnotation]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/DownloadHistory.jsm :: updateMetaData :: line 82"  data: no]  （未知）`

I found some sort of similar issue on [bug-1298362](https://bug635044.bugzilla.mozilla.org/show_bug.cgi?id=1298362), but bug description says file download works normal, just raise an error in process.
So do you sure there's no issues with downloads? If this issue caused by a places corruption, it might be profile-wide.

**Comment by Arrow-Li** [comment] 2017-08-13 07:36
Save erroe log is working fine.
![default](https://user-images.githubusercontent.com/17962902/29247696-01323c4e-803d-11e7-95d3-64871cbbe038.png)
The browser console show this 
![123](https://user-images.githubusercontent.com/17962902/29247703-1ac29d2a-803d-11e7-9fad-2ed4d0053353.gif)

**Comment by Arrow-Li** [comment] 2017-08-13 07:44
Seems the error is 

> Error: WebExtension context not found!  ExtensionParent.jsm:778:13

**Comment by FelisCatus** [comment] 2017-08-14 19:57
Seems to be Firefox's issue. As always, try the most recent Nightly build and other issues.

There's a possible explanation that the WebExtension context is not loaded on the options page context but loads fine on the background page. I have no idea how that is possible since the options page should also be considered part of the extension. Plus, for some reason, it works for me.

**Comment by Arrow-Li** [comment] 2017-08-16 03:34
So we can only waiting Firefox new update...

**Comment by Arrow-Li** [comment] 2017-09-08 05:30
Button works fine with 56.0b9 Switchy 2.5.2, seems bug fixed.

**Comment by FelisCatus** [comment] 2017-09-10 08:23
Good to hear that. Closing this for now. Please comment if this still affects you.

**Closed by FelisCatus** 2017-09-10 08:23 UTC
