### ISSUE TITLE
Firefox: Direct does not override system proxy settings

### ISSUE THREAD

**Issue by gloomy-ghost** [FelisCatus/SwitchyOmega#1212] opened 2017-09-09 12:41 UTC
Tested on Nightly 2017-09-08

STR:
1. Set proxy in system settings
2. Set "Direct" in SwitchyOmega
3. Open https://icanhazip.com/ (or any site that gives the client ip)

Expected:
The client IP should be shown

Actual:
The proxy IP was shown

**Comment by FelisCatus** [comment] 2017-09-10 08:30
Sounds like a Mozilla problem. But anyway:

1. Does selecting a proxy profile work? I mean, when you select a proxy profile in the SwitchyOmega dropdown, does it use that proxy instead of system proxy?
  * Even if you don't have a proxy, you can still use `127.0.0.1:8888`, etc. to test. If it says fail to connect tot proxy then the settings are indeed applied.
  * If nothing works, then you are probably affected by #1171.
2. If yes, could you please try right-clicking on the SO icon and select Save error log? You can directly upload the file here.
  * See if `icanhazip.com` is in the log.
  * The log should not contain any confidential information, but please double check and remove anything as you see fit and put a comment there.

**Comment by gloomy-ghost** [comment] 2017-09-10 09:06
1. Selecting a proxy profile works.
2. The log seems not very informative, actually I don't see any domains at all. Not sure if I am doing it correctly. 
[OmegaLog_1505034118193.txt](https://github.com/FelisCatus/SwitchyOmega/files/1290388/OmegaLog_1505034118193.txt)

**Comment by olloff** [comment] 2017-09-10 10:43
Can't confirm this with FF 57.0.a1 (current nightly) and FF 55.0.0.3 on Win10 x64.
SwitchyOmega 2.5.2

When _Direct_ profile is selected, FF correctly follows the browser proxy settings (network.proxy.type). 
If _No proxy_ being selected (network.proxy.type; 0), icanhazip.com displays my NAT ip.
If _Use system proxy_ being selected (network.proxy.type; 5), icanhazip.com displays my proxy ip from system settings.
If _Manual proxy configuration_ being selected (network.proxy.type; 1), icanhazip.com displays my proxy ip from browser settings.

**Comment by gloomy-ghost** [comment] 2017-09-10 21:53
> When Direct profile is selected, FF correctly follows the browser proxy settings

Is this behavior expected? Does it mean that either _system_ does not work (while selecting _No proxy_ in Fx) or _direct_ does not work (while selecting _Use system proxy_ in Fx)? IIRC, _direct_ overrides the browser proxy setting in Chrome rather than giving back control to the browser.

**Comment by olloff** [comment] 2017-09-10 22:10
> direct overrides the browser proxy setting in Chrome
I always thought there is no browser proxy settings in Chrome and it always use system ones. So either in FF or Chrome it means _ignore system settings, skip to the next layer_

**Comment by gloomy-ghost** [comment] 2017-09-10 23:20
Yeah Chrome uses the system setting, and what do I meant by overriding is connecting directly regardless of any proxy configuration.

**Comment by FelisCatus** [comment] 2017-09-11 17:27
I can reproduce this.

This is unexpected since I believe selecting `[Direct]` should override anything else. But if this is how it works in Firefox then I don't think I can do anything about it.

**Comment by FelisCatus** [comment] 2017-09-11 19:20
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1398900.

**Comment by caoli5288** [comment] 2017-09-22 19:41
Not only DIRECT but also other proxy mode will use system's proxy settings.

**Comment by coiby** [comment] 2017-12-08 12:27
I can reproduce this issue.

**Comment by FelisCatus** [comment] 2017-12-12 00:19
@coiby Now it is at the point that someone needs to propose a patch on the Firefox issue linked above. Otherwise, there is nothing we can do on SwitchyOmega's side. You can also help if you want.

**Comment by lbonvarl** [comment] 2018-03-26 08:57
Any follow up on this ? Direct use system proxy setting still on Firefox 59. This is different from Chrome. Ability to switch between direct and proxy config is the main advantage of switchy Omega

**Comment by FelisCatus** [comment] 2018-03-29 04:34
@lbonvarl I would love to make it work the same as Chrome, but as I've mentioned, now it is all up to Firefox.

**Comment by FelisCatus** [comment] 2018-07-09 05:39
This is probably fixed in #1456. Please try SwitchyOmega v2.5.16 (Firefox ONLY).

**Closed by FelisCatus** 2018-07-09 05:39 UTC
