### ISSUE TITLE
Proxy Not connecting

### ISSUE THREAD

**Issue by Ryuakuma** [FelisCatus/SwitchyOmega#239] opened 2015-01-27 14:30 UTC
The proxies I use aren't working. They work for some websites, but on others it doesn't load and says it can't connect to the Proxy Server...

SwitchyOmega 2.3.0
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.65 Safari/537.36

**Comment by FelisCatus** [comment] 2015-01-28 07:16
1. Please upload a screenshot of your Proxy Profile settings. You may mask the server address or change some of the digits to protect your privacy.
2. Please give an example of a working website, and a failing website. Specify full URLs please.
3. If you are using Switch Profile, please provide a screenshot of that as well.

I would also like to kindly remind you that this is an Issue Tracker, which is designed for solving issues instead of collecting feedback. Please, at least, give some information so that others can help you to get it working.

**Comment by gip0** [comment] 2015-02-20 22:57
see #279 for setup instructions

**Comment by FelisCatus** [comment] 2015-02-21 02:45
I'm closing this issue for the following reasons:

1. This is certainly caused by wrong configuration in Proxy Profile. Either the host and port settings is wrong, or the proxy server is not responding or does not exist.
2. No details or feedback is provided in the last four weeks.

**Closed by FelisCatus** 2015-02-21 02:45 UTC
